### ISSUE TITLE
Bedlam dataset for training

### ISSUE THREAD

**Issue by Maskros-new** [ttxskk/AiOS#21]
Hi, 

I downloaded `Synthetic Image Data at 6fps used for training and testing` from BEDLAM website and used the `preprocessed_npz` file you provided for training.

In the official dataset, there are files like `20221019_1_250_highbmihand_closeup_suburb_b_6fps`. However, while fetching data during training, the required path is `20221019_1_250_highbmihand_suburb_b_6fps`, w/o the "closeup" flag, resulting in OSError. 

Observing the description document of the bedlam dataset, I found that `closeup`  flag means a version of the image rotated 90 degrees, but they did not provide training data like `20221019_1_250_highbmihand_suburb_b_6fps`.  I'm wondering what steps I'm missing? Thank u!

ps:
my BEDLAM train_image folder:
├── 20221010_3_1000_batch01hand_6fps
├── 20221010_3-10_500_batch01hand_zoom_suburb_d_6fps
├── 20221011_1_250_batch01hand_closeup_suburb_a_6fps
├── 20221011_1_250_batch01hand_closeup_suburb_b_6fps
├── 20221011_1_250_batch01hand_closeup_suburb_c_6fps
├── 20221011_1_250_batch01hand_closeup_suburb_d_6fps
├── 20221012_1_500_batch01hand_closeup_highSchoolGym_6fps
├── 20221012_3-10_500_batch01hand_zoom_highSchoolGym_6fps
├── 20221013_3-10_500_batch01hand_static_highSchoolGym_6fps
├── 20221013_3_250_batch01hand_orbit_bigOffice_6fps
├── 20221013_3_250_batch01hand_static_bigOffice_6fps
├── 20221014_3_250_batch01hand_orbit_archVizUI3_time15_6fps
├── 20221015_3_250_batch01hand_orbit_archVizUI3_time10_6fps
├── 20221015_3_250_batch01hand_orbit_archVizUI3_time12_6fps
├── 20221015_3_250_batch01hand_orbit_archVizUI3_time19_6fps
├── 20221017_3_1000_batch01hand_6fps
├── 20221018_1_250_batch01hand_zoom_suburb_b_6fps
├── 20221018_3_250_batch01hand_orbit_archVizUI3_time15_6fps
├── 20221018_3-8_250_batch01hand_6fps
├── 20221018_3-8_250_batch01hand_pitchDown52_stadium_6fps
├── 20221018_3-8_250_batch01hand_pitchUp52_stadium_6fps
├── 20221019_1_250_highbmihand_closeup_suburb_b_6fps
├── 20221019_1_250_highbmihand_closeup_suburb_c_6fps
├── 20221019_3_250_highbmihand_6fps
├── 20221019_3-8_1000_highbmihand_static_suburb_d_6fps
├── 20221019_3-8_250_highbmihand_orbit_stadium_6fps
├── 20221020-3-8_250_highbmihand_zoom_highSchoolGym_a_6fps

training log:
Original Traceback (most recent call last):
  File "/mnt/data1/user/miniconda3/envs/closeint/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/data1/user/miniconda3/envs/closeint/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/data1/user/miniconda3/envs/closeint/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data1/data1/user/workspace/AiOS/datasets/dataset.py", line 39, in __getitem__
    return self.dataset[k[i]][index % len(self.dataset[k[i]])]
  File "/data1/data1/user/workspace/AiOS/datasets/humandata.py", line 491, in __getitem__
    img = load_img(img_path, order='BGR')
  File "/data1/data1/user/workspace/AiOS/util/preprocessing.py", line 15, in load_img
    raise IOError('Fail to read %s' % path)
OSError: Fail to read ./data/datasets/bedlam/train_images/20221019_1_250_highbmihand_suburb_b_6fps/png/seq_000161/seq_000161_0055.png

**Comment by ttxskk** [comment]
Hi @Maskros-new ,
Sorry for this. I had made some changes to the close-up images by rotating them 90 degrees and removing "closeup" from the folder names.
