### ISSUE TITLE
Issues Installing 

### ISSUE THREAD

**Issue by keniel123** [ttxskk/AiOS#23]
Hi I am trying to run the Build deformable detr steps but I am getting the below error 

`(aios) C:\Users\krp1n21\Downloads\AiOS\models\aios\ops>python setup.py build installrunning buildrunning build_pycopying functions\ms_deform_attn_func.py -> build\lib.win-amd64-cpython-38\functionscopying functions\__init__.py -> build\lib.win-amd64-cpython-38\functionscopying modules\ms_deform_attn.py -> build\lib.win-amd64-cpython-38\modulescopying modules\ms_deform_attn_key_aware.py -> build\lib.win-amd64-cpython-38\modulescopying modules\__init__.py -> build\lib.win-amd64-cpython-38\modulesrunning build_extbuilding 'MultiScaleDeformableAttention' extensionEmitting ninja build file C:\Users\krp1n21\Downloads\AiOS\models\aios\ops\build\temp.win-amd64-cpython-38\Release\build.ninja...Compiling objects...Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)[1/1] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\krp1n21\Downloads\AiOS\models\aios\ops\build\temp.win-amd64-cpython-38\Release\Users\krp1n21\Downloads\AiOS\models\aios\ops\src\cuda\ms_deform_attn_cuda.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\Users\krp1n21\Downloads\AiOS\models\aios\ops\src -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\include -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\include\TH -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\include -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" -c C:\Users\krp1n21\Downloads\AiOS\models\aios\ops\src\cuda\[ms_deform_attn_cuda.cu](http://ms_deform_attn_cuda.cu/) -o C:\Users\krp1n21\Downloads\AiOS\models\aios\ops\build\temp.win-amd64-cpython-38\Release\Users\krp1n21\Downloads\AiOS\models\aios\ops\src\cuda\ms_deform_attn_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MultiScaleDeformableAttention -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75FAILED: C:/Users/krp1n21/Downloads/AiOS/models/aios/ops/build/temp.win-amd64-cpython-38/Release/Users/krp1n21/Downloads/AiOS/models/aios/ops/src/cuda/ms_deform_attn_cuda.objC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\krp1n21\Downloads\AiOS\models\aios\ops\build\temp.win-amd64-cpython-38\Release\Users\krp1n21\Downloads\AiOS\models\aios\ops\src\cuda\ms_deform_attn_cuda.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\Users\krp1n21\Downloads\AiOS\models\aios\ops\src -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\include -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\include\TH -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\include -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" -c C:\Users\krp1n21\Downloads\AiOS\models\aios\ops\src\cuda\[ms_deform_attn_cuda.cu](http://ms_deform_attn_cuda.cu/) -o C:\Users\krp1n21\Downloads\AiOS\models\aios\ops\build\temp.win-amd64-cpython-38\Release\Users\krp1n21\Downloads\AiOS\models\aios\ops\src\cuda\ms_deform_attn_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MultiScaleDeformableAttention -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include\crt/host_config.h(153): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.[ms_deform_attn_cuda.cu](http://ms_deform_attn_cuda.cu/)ninja: build stopped: subcommand failed.Traceback (most recent call last):  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\utils\cpp_extension.py", line 1893, in _run_ninja_build    subprocess.run(  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\subprocess.py", line 516, in run    raise CalledProcessError(retcode, process.args,subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):  File "setup.py", line 64, in <module>    setup(  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\__init__.py", line 117, in setup    return distutils.core.setup(**attrs)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\core.py", line 183, in setup    return run_commands(dist)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\core.py", line 199, in run_commands    dist.run_commands()  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\dist.py", line 954, in run_commands    self.run_command(cmd)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\dist.py", line 950, in run_command    super().run_command(command)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command    cmd_obj.run()  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run    self.run_command(cmd_name)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command    self.distribution.run_command(command)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\dist.py", line 950, in run_command    super().run_command(command)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command    cmd_obj.run()  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\command\build_ext.py", line 98, in run    _build_ext.run(self)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run    self.build_extensions()  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\utils\cpp_extension.py", line 843, in build_extensions    build_ext.build_extensions(self)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 476, in build_extensions    self._build_extensions_serial()  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 502, in _build_extensions_serial    self.build_extension(ext)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\command\build_ext.py", line 263, in build_extension    _build_ext.build_extension(self, ext)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 557, in build_extension    objects = self.compiler.compile(  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\utils\cpp_extension.py", line 815, in win_wrap_ninja_compile    _write_ninja_file_and_compile_objects(  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\utils\cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects    _run_ninja_build(  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\utils\cpp_extension.py", line 1909, in _run_ninja_build    raise RuntimeError(message) from eRuntimeError: Error compiling objects for extension
(aios) C:\Users\krp1n21\Downloads\AiOS\models\aios\ops>python setup.py build installrunning buildrunning build_pycopying functions\ms_deform_attn_func.py -> build\lib.win-amd64-cpython-38\functionscopying functions\__init__.py -> build\lib.win-amd64-cpython-38\functionscopying modules\ms_deform_attn.py -> build\lib.win-amd64-cpython-38\modulescopying modules\ms_deform_attn_key_aware.py -> build\lib.win-amd64-cpython-38\modulescopying modules\__init__.py -> build\lib.win-amd64-cpython-38\modulesrunning build_extbuilding 'MultiScaleDeformableAttention' extensionEmitting ninja build file C:\Users\krp1n21\Downloads\AiOS\models\aios\ops\build\temp.win-amd64-cpython-38\Release\build.ninja...Compiling objects...Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)[1/1] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\krp1n21\Downloads\AiOS\models\aios\ops\build\temp.win-amd64-cpython-38\Release\Users\krp1n21\Downloads\AiOS\models\aios\ops\src\cuda\ms_deform_attn_cuda.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\Users\krp1n21\Downloads\AiOS\models\aios\ops\src -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\include -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\include\TH -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\include -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" -c C:\Users\krp1n21\Downloads\AiOS\models\aios\ops\src\cuda\[ms_deform_attn_cuda.cu](http://ms_deform_attn_cuda.cu/) -o C:\Users\krp1n21\Downloads\AiOS\models\aios\ops\build\temp.win-amd64-cpython-38\Release\Users\krp1n21\Downloads\AiOS\models\aios\ops\src\cuda\ms_deform_attn_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MultiScaleDeformableAttention -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75FAILED: C:/Users/krp1n21/Downloads/AiOS/models/aios/ops/build/temp.win-amd64-cpython-38/Release/Users/krp1n21/Downloads/AiOS/models/aios/ops/src/cuda/ms_deform_attn_cuda.objC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc --generate-dependencies-with-compile --dependency-output C:\Users\krp1n21\Downloads\AiOS\models\aios\ops\build\temp.win-amd64-cpython-38\Release\Users\krp1n21\Downloads\AiOS\models\aios\ops\src\cuda\ms_deform_attn_cuda.obj.d --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\Users\krp1n21\Downloads\AiOS\models\aios\ops\src -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\include -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\include\TH -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\include -IC:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" -c C:\Users\krp1n21\Downloads\AiOS\models\aios\ops\src\cuda\[ms_deform_attn_cuda.cu](http://ms_deform_attn_cuda.cu/) -o C:\Users\krp1n21\Downloads\AiOS\models\aios\ops\build\temp.win-amd64-cpython-38\Release\Users\krp1n21\Downloads\AiOS\models\aios\ops\src\cuda\ms_deform_attn_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=MultiScaleDeformableAttention -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include\crt/host_config.h(153): fatal error C1189: #error:  -- unsupported Microsoft Visual Studio version! Only the versions between 2017 and 2022 (inclusive) are supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.[ms_deform_attn_cuda.cu](http://ms_deform_attn_cuda.cu/)ninja: build stopped: subcommand failed.Traceback (most recent call last):  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\utils\cpp_extension.py", line 1893, in _run_ninja_build    subprocess.run(  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\subprocess.py", line 516, in run    raise CalledProcessError(retcode, process.args,subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):  File "setup.py", line 64, in <module>    setup(  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\__init__.py", line 117, in setup    return distutils.core.setup(**attrs)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\core.py", line 183, in setup    return run_commands(dist)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\core.py", line 199, in run_commands    dist.run_commands()  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\dist.py", line 954, in run_commands    self.run_command(cmd)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\dist.py", line 950, in run_command    super().run_command(command)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command    cmd_obj.run()  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run    self.run_command(cmd_name)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command    self.distribution.run_command(command)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\dist.py", line 950, in run_command    super().run_command(command)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command    cmd_obj.run()  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\command\build_ext.py", line 98, in run    _build_ext.run(self)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run    self.build_extensions()  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\utils\cpp_extension.py", line 843, in build_extensions    build_ext.build_extensions(self)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 476, in build_extensions    self._build_extensions_serial()  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 502, in _build_extensions_serial    self.build_extension(ext)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\command\build_ext.py", line 263, in build_extension    _build_ext.build_extension(self, ext)  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 557, in build_extension    objects = self.compiler.compile(  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\utils\cpp_extension.py", line 815, in win_wrap_ninja_compile    _write_ninja_file_and_compile_objects(  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\utils\cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects    _run_ninja_build(  File "C:\Users\krp1n21\AppData\Local\anaconda3\envs\aios\lib\site-packages\torch\utils\cpp_extension.py", line 1909, in _run_ninja_build    raise RuntimeError(message) from eRuntimeError: Error compiling objects for extension`

**Comment by ttxskk** [comment]
Hi @keniel123 , our code hasn't been tested under Windows, and would you mind trying it with the WSL?
